version: '3.9'

services:
  frontend:
    build: ./frontend
    ports:
      - 8501:8501
    depends_on:
      - backend
    volumes:
        - ./tmp/save:/tmp/save
  backend:
    build: ./backend
    ports:
      - 8081:8081
